using System;
using System.IO;
using System.Text;

namespace BGOverlay.Resources
{
    public class EffectEntry
    {
        public EffectEntry(BinaryReader reader, int offset)
        {
            offset += 8;
            reader.BaseStream.Seek(offset, SeekOrigin.Begin);
            var opcode = reader.ReadInt32();
            reader.ReadInt64();
            this.Param1 = reader.ReadInt32();
            this.Param2 = reader.ReadInt32();

            reader.BaseStream.Seek(offset + 0x0030 - 16, SeekOrigin.Begin);
            try 
            {
                var bytes = reader.ReadBytes(8);
                this.Resource = Encoding.UTF8.GetString(bytes);
            } catch (Exception ex)
            {
                var msg = ex.Message;
            }
            this.EffectName = (Effect)opcode;

            reader.BaseStream.Seek(offset + 0x0094 - 16, SeekOrigin.Begin);
            this.ParentResource = new string(reader.ReadChars(8));

            reader.BaseStream.Seek(offset + 0x0060 - 16, SeekOrigin.Begin);
            this.Param3 = reader.ReadInt32();
            this.Param4 = reader.ReadInt32();
            this.Param5 = reader.ReadInt32();
            this.Param6 = reader.ReadInt32();
            this.Resource2 = new string(reader.ReadChars(8));
            this.Resource3 = new string(reader.ReadChars(8));

            reader.BaseStream.Seek(offset + 0x00A8 - 16, SeekOrigin.Begin);
            this.VariableName = new string(reader.ReadChars(32));
        }

        public override string ToString()
        {
            return $"{EffectName} : {ParentResource}";
        }

        public int Param1 { get; }
        public int Param2 { get; }
        public string Resource { get; }
        public Effect EffectName { get; }
        public string ParentResource { get; }
        public int Param3 { get; }
        public int Param4 { get; }
        public int Param5 { get; }
        public int Param6 { get; }
        public string Resource2 { get; }
        public string Resource3 { get; }
        public string VariableName { get; }
    }

    public enum Proficiency
    {
        BASTARDSWORD                               = 89,
        LONGSWORD                                  = 90,
        SHORTSWORD                                 = 91,
        AXE                                        = 92,
        TWOHANDEDSWORD                             = 93,
        KATANA                                     = 94,
        SCIMITARWAKISASHININJATO                   = 95,
        DAGGER                                     = 96,
        WARHAMMER                                  = 97,
        SPEAR                                      = 98,
        HALBERD                                    = 99,
        FLAILMORNINGSTAR                           = 100,
        MACE                                       = 101,
        QUARTERSTAFF                               = 102,
        CROSSBOW                                   = 103,
        LONGBOW                                    = 104,
        SHORTBOW                                   = 105,
        DART                                       = 106,
        SLING                                      = 107,
        BLACKJACK                                  = 108,
        CLERIC_HALLOW                              = 109,
        CLERIC_ARMOR_OF_FAITH                      = 110,
        TWOHANDED                                  = 111,
        SWORDANDSHIELD                             = 112,
        SINGLEWEAPON                               = 113,
        TWOWEAPON                                  = 114,
        CLUB                                       = 115,
        WIZARD_SPELL_DEFLECTION                    = 116,
        PROTECTION_FROM_EVIL                       = 117,
        TRUE_SIGHT                                 = 118,
        CLERIC_CHAOTIC_COMMANDS                    = 119,
        CLERIC_INSECT_PLAGUE                       = 120,
        CLERIC_BLADE_BARRIER                       = 121,
        CLERIC_PHYSICAL_MIRROR                     = 122,
        CLERIC_SHIELD_OF_THE_ARCHONS               = 123,
        CLERIC_REGENERATION                        = 124,
        WIZARD_FIRE_SHIELD                         = 125,
        WIZARD_PROTECTION_FROM_MAGIC_ENERGY        = 126,
        WIZARD_MISLEAD                             = 127,
        WIZARD_PROTECTION_FROM_MAGIC_WEAPONS       = 128,
        WIZARD_SPELL_TURNING                       = 129,
        WIZARD_PROTECTION_FROM_THE_ELEMENTS        = 130,
        CLERIC_FREE_ACTION                         = 131,
        WIZARD_KHELBENS_WARDING_WHIP               = 132,
        CLERIC_DEFENSIVE_HARMONY                   = 133,
        EXTRA20                                    = 134
    }

    public enum Effect
    {
        Stat_AC_vs_Damage_Type_Modifier                              = 0,
        Stat_Attacks_Per_Round_Modifier                              = 1,
        Cure_Sleep                                                   = 2,
        State_Berserking                                             = 3,
        Cure_Berserking                                              = 4,
        Charm_Charm_Specific_Creature                                = 5,
        Stat_Charisma_Modifier                                       = 6,
        Colour_Set_Character_colours_by_Palette                      = 7,
        Colour_Change_by_RGB                                         = 8,
        Colour_Glow_Pulse                                            = 9,
        Stat_Constitution_Modifier                                   = 10,
        Cure_Poison                                                  = 11,
        HP_Damage                                                    = 12,
        Death_Instant_Death                                          = 13,
        Graphics_Defrost                                             = 14,
        Stat_Dexterity_Modifier                                      = 15,
        State_Haste                                                  = 16,
        HP_Current_HP_Modifier                                       = 17,
        HP_Maximum_HP_Modifier                                       = 18,
        Stat_Intelligence_Modifier                                   = 19,
        State_Invisibility                                           = 20,
        Stat_Lore_Modifier                                           = 21,
        Stat_Cumulative_Luck_Bonus                                   = 22,
        Stat_Morale_Modifier                                         = 23,
        State_Horror                                                 = 24,
        State_Poison                                                 = 25,
        Item_Remove_Curse                                            = 26,
        Stat_Acid_Resistance_Modifier                                = 27,
        Stat_Cold_Resistance_Modifier                                = 28,
        Stat_Electricity_Resistance_Modifier                         = 29,
        Stat_Fire_Resistance_Modifier                                = 30,
        Stat_Magic_Damage_Resistance_Modifier                        = 31,
        Cure_Death_Raise_Dead                                        = 32,
        Stat_Save_vs_Death_Modifier                                  = 33,
        Stat_Save_vs_Wands_Modifier                                  = 34,
        Stat_Save_vs_Petrification_or_Polymorph_Modifier             = 35,
        Stat_Save_vs_Breath_Weapons_Modifier                         = 36,
        Stat_Save_vs_Spells_Modifier                                 = 37,
        State_Silence                                                = 38,
        State_Unconsciousness                                        = 39,
        State_Slow                                                   = 40,
        Graphics_Sparkle                                             = 41,
        Spell_Wizard_Spell_Slots_Modifier                            = 42,
        Cure_Stone_to_Flesh                                          = 43,
        Stat_Strength_Modifier                                       = 44,
        State_Stun                                                   = 45,
        Cure_Stun_Unstun                                             = 46,
        Cure_Invisibility                                            = 47,
        Cure_Silence_Vocalize                                        = 48,
        Stat_Wisdom_Modifier                                         = 49,
        Colour_Glow_by_RGB_Brief                                     = 50,
        Colour_Strong_or_Dark_by_RGB                                 = 51,
        Colour_Very_Bright_by_RGB                                    = 52,
        Graphics_Animation_Change                                    = 53,
        Stat_THAC0_Modifier                                          = 54,
        Death_Kill_Creature_Type                                     = 55,
        Alignment_Invert                                             = 56,
        Alignment_Change                                             = 57,
        Cure_Dispellable_Effects_Dispel_Magic                        = 58,
        Stat_Stealth_Modifier                                        = 59,
        Stat_Miscast_Magic                                           = 60,
        Creature_RGB_color_fade                                      = 61,
        Spell_Priest_Spell_Slots_Modifier                            = 62,
        State_Infravision                                            = 63,
        State_Remove_Infravision                                     = 64,
        Overlay_Blur                                                 = 65,
        Graphics_Transparency_Fade                                   = 66,
        Summon_Creature_Summoning                                    = 67,
        Summon_Unsummon_Creature                                     = 68,
        Protection_From_Detection_NonDetection                       = 69,
        Cure_NonDetection                                            = 70,
        IDS_Sex_Change                                               = 71,
        IDS_Set_IDS_State                                            = 72,
        Stat_Extra_Damage_Modifier                                   = 73,
        State_Blindness                                              = 74,
        Cure_Blindness                                               = 75,
        State_Feeblemindedness                                       = 76,
        Cure_Feeblemindedness                                        = 77,
        State_Disease                                                = 78,
        Cure_Disease                                                 = 79,
        State_Deafness                                               = 80,
        Cure_Deafness                                                = 81,
        Set_AI_Script                                                = 82,
        Protection_From_Projectile                                   = 83,
        Stat_Magical_Fire_Resistance_Modifier                        = 84,
        Stat_Magical_Cold_Resistance_Modifier                        = 85,
        Stat_Slashing_Resistance_Modifier                            = 86,
        Stat_Crushing_Resistance_Modifier                            = 87,
        Stat_Piercing_Resistance_Modifier                            = 88,
        Stat_Missiles_Resistance_Modifier                            = 89,
        Stat_Open_Locks_Modifier                                     = 90,
        Stat_Find_Traps_Modifier                                     = 91,
        Stat_Pick_Pockets_Modifier                                   = 92,
        Stat_Fatigue_Modifier                                        = 93,
        Stat_Drunkenness_Modifier                                    = 94,
        Stat_Tracking_Skill_Modifier                                 = 95,
        Stat_Level_Change                                            = 96,
        Stat_Exceptional_Strength_Modifier                           = 97,
        HP_Regeneration                                              = 98,
        Spell_Effect_Duration_Modifier                               = 99,
        Protection_from_Creature_Type                                = 100,
        Protection_from_Opcode                                       = 101,
        Spell_Immunity_by_Power_Level                                = 102,
        Text_Change_Name                                             = 103,
        Stat_Experience_Points                                       = 104,
        Stat_Gold                                                    = 105,
        Stat_Morale_Break_Modifier                                   = 106,
        Portrait_Change                                              = 107,
        Stat_Reputation                                              = 108,
        State_Paralyze                                               = 109,
        Item_Create_Magical_Weapon                                   = 111,
        Item_Remove_Item                                             = 112,
        Graphics_Dither                                              = 114,
        Detect_Alignment                                             = 115,
        State_Cure_Invisibility                                      = 116,
        Spell_Effect_Reveal_Area                                     = 117,
        Spell_Effect_Mirror_Image                                    = 119,
        Protection_from_Weapons                                      = 120,
        Item_Create_Inventory_Item                                   = 122,
        Item_Remove_Inventory_Item                                   = 123,
        Spell_Effect_Teleport_Dimension_Door                         = 124,
        Spell_Effect_Unlock_Knock                                    = 125,
        Stat_Movement_Modifier                                       = 126,
        Summon_Monster_Summoning                                     = 127,
        State_Confusion                                              = 128,
        State_Aid                                                    = 129,
        State_Bless                                                  = 130,
        State_Positive_Chant                                         = 131,
        State_Raise_Strength_Constitution__Dexterity_NonCumulative   = 132,
        Spell_Effect_Luck_NonCumulative                              = 133,
        State_Petrification                                          = 134,
        Graphics_Polymorph_into_Specific                             = 135,
        State_Force_Visible                                          = 136,
        State_Negative_Chant                                         = 137,
        Graphics_Character_Animation_Change                          = 138,
        Text_Display_String                                          = 139,
        Graphics_Casting_Glow                                        = 140,
        Graphics_Lighting_Effects                                    = 141,
        Graphics_Display_Special_Effect_Icon                         = 142,
        Item_Create_Item_in_Slot                                     = 143,
        Button_Disable_Button                                        = 144,
        Spell_Disable_Spell_Casting_Abilities                        = 145,
        Spell_Cast_Spell_at_Creature                                 = 146,
        Spell_Learn_Spell                                            = 147,
        Spell_Cast_Spell_at_Point                                    = 148,
        Identify                                                     = 149,
        Spell_Effect_Find_Traps                                      = 150,
        Summon_Replace_Creature                                      = 151,
        Spell_Effect_Play_Movie                                      = 152,
        Overlay_Sanctuary                                            = 153,
        Overlay_Entangle                                             = 154,
        Overlay_Minor_Globe                                          = 155,
        Overlay_Protection_from_Normal_Missiles_Cylinder             = 156,
        State_Web_Effect                                             = 157,
        Overlay_Grease                                               = 158,
        Spell_Effect_Mirror_Image_Exact_Number                       = 159,
        Remove_Sanctuary                                             = 160,
        Cure_Horror                                                  = 161,
        Cure_Hold                                                    = 162,
        Protection_Free_Action                                       = 163,
        Cure_Drunkeness                                              = 164,
        Spell_Effect_Pause_Target                                    = 165,
        Stat_Magic_Resistance_Modifier                               = 166,
        Stat_THAC0_Modifier_with_Missile_Weapons                     = 167,
        Summon_Remove_Creature                                       = 168,
        Graphics_Prevent_Special_Effect_Icon                         = 169,
        Graphics_Play_Damage_Animation                               = 170,
        Spell_Give_Ability                                           = 171,
        Spell_Remove_Spell                                           = 172,
        Stat_Poison_Resistance_Modifier                              = 173,
        Spell_Effect_Play_Sound_Effect                               = 174,
        State_Hold                                                   = 175,
        Stat_Movement_Modifier_II                                    = 176,
        Use_EFF_File                                                 = 177,
        Spell_Effect_THAC0_vs_Creature_Type_Modifier                 = 178,
        Spell_Effect_Damage_vs_Creature_Type_Modifier                = 179,
        Item_Cant_Use_Item                                           = 180,
        Item_Cant_Use_Itemtype                                       = 181,
        Item_Apply_Effect_Item                                       = 182,
        Item_Apply_Effect_Itemtype                                   = 183,
        Graphics_Passwall_Dont_Jump                                  = 184,
        State_Hold_II                                                = 185,
        Script_MoveToArea                                            = 186,
        Script_Store_Local_Variable                                  = 187,
        Spell_Effect_Aura_Cleansing                                  = 188,
        Stat_Casting_Time_Modifier                                   = 189,
        Stat_Attack_Speed_Factor                                     = 190,
        Spell_Casting_Level_Modifier                                 = 191,
        Spell_Effect_Find_Familiar                                   = 192,
        Spell_Effect_Invisible_Detection_by_Script                   = 193,
        Ignore_Dialog_Pause                                          = 194,
        Spell_Effect_Death_Dependent_Constitution_Loss_Familiar_Bond = 195,
        Spell_Effect_Familiar_Block                                  = 196,
        Spell_Bounce_by_Impact_Projectile                            = 197,
        Spell_Bounce_by_Opcode                                       = 198,
        Spell_Bounce_by_Power_Level                                  = 199,
        Spell_Bounce_by_Power_level_decrementing                     = 200,
        Spell_Immunity_by_Power_Level_decrementing                   = 201,
        Spell_Bounce_by_School                                       = 202,
        Spell_Bounce_by_Secondary_Type                               = 203,
        Spell_Protection_by_School                                   = 204,
        Spell_Protection_by_Secondary_Type                           = 205,
        Spell_Protection_from_Spell                                  = 206,
        Spell_Bounce_by_Resource                                     = 207,
        HP_Minimum_Limit                                             = 208,
        Death_Kill_60HP                                              = 209,
        Spell_Effect_Stun_90HP                                       = 210,
        Spell_Effect_Imprisonment                                    = 211,
        Protection_Freedom                                           = 212,
        Spell_Effect_Maze                                            = 213,
        Spell_Effect_Select_Spell                                    = 214,
        Graphics_Play_3D_Effect                                      = 215,
        Spell_Effect_Level_Drain                                     = 216,
        Spell_Effect_Unconsciousness_20HP                            = 217,
        Protection_Stoneskin                                         = 218,
        Stat_AC_vs_Creature_Type_Modifier                            = 219,
        Removal_Remove_School                                        = 220,
        Removal_Remove_Secondary_Type                                = 221,
        Spell_Effect_Teleport_Field                                  = 222,
        Spell_Immunity_by_School_decrementing                        = 223,
        Cure_Level_Drain_Restoration                                 = 224,
        Spell_Reveal_Magic                                           = 225,
        Spell_Immunity_by_Secondary_Type_decrementing                = 226,
        Spell_Bounce_by_School_decrementing                          = 227,
        Spell_Bounce_by_Secondary_Type_decrementing                  = 228,
        Removal_Remove_One_School                                    = 229,
        Removal_Remove_One_Secondary_Type                            = 230,
        Spell_Effect_Time_Stop                                       = 231,
        Spell_Effect_Cast_Spell_on_Condition                         = 232,
        Stat_Proficiency_Modifier                                    = 233,
        Spell_Effect_Contingency_Creation                            = 234,
        Spell_Effect_Wing_Buffet                                     = 235,
        Spell_Effect_Image_Projection                                = 236,
        Spell_Effect_Puppet_ID                                       = 237,
        Death_Disintegrate                                           = 238,
        Spell_Effect_Farsight                                        = 239,
        Graphics_Remove_Special_Effect_Icon                          = 240,
        Charm_Control_Creature                                       = 241,
        Cure_Confusion                                               = 242,
        Item_Drain_Item_Charges                                      = 243,
        Spell_Drain_Wizard_Spell                                     = 244,
        Check_For_Berserk                                            = 245,
        Spell_Effect_Berserking                                      = 246,
        Spell_Effect_Attack_Nearest_Creature                         = 247,
        Item_Set_Melee_Effect                                        = 248,
        Item_Set_Ranged_Effect                                       = 249,
        Spell_Effect_Damage_Modifier                                 = 250,
        Spell_Effect_Change_Bard_Song_Effect                         = 251,
        Spell_Effect_Set_Trap                                        = 252,
        Spell_Effect_Add_Map_Marker                                  = 253,
        Spell_Effect_Remove_Map_Marker                               = 254,
        Item_Create_Inventory_Item_days                              = 255,
        Spell_Spell_Sequencer_Active                                 = 256,
        Spell_Spell_Sequencer_Creation                               = 257,
        Spell_Spell_Sequencer_Activation                             = 258,
        Protection_Spell_Trap_by_Power_Level_decrementing            = 259,
        Spell_Spell_Sequencer_Activation2                            = 260,
        Spell_Restore_Lost_Spells                                    = 261,
        Stat_Visual_Range                                            = 262,
        Stat_Backstab                                                = 263,
        Spell_Effect_Drop_Weapons_in_Panic                           = 264,
        Script_Modify_Global_Variable                                = 265,
        Spell_Remove_Protection_from_Spell                           = 266,
        Text_Protection_from_Display_Specific_String                 = 267,
        Spell_Effect_Clear_Fog_of_War_Wizard_Eye                     = 268,
        Spell_Effect_Shake_Window                                    = 269,
        Cure_Unpause_Target                                          = 270,
        Graphics_Avatar_Removal                                      = 271,
        Spell_Apply_Repeating_EFF                                    = 272,
        Remove_Specific_Area_EffectZone_of_Sweet_Air                 = 273,
        Spell_Effect_Teleport_to_Target                              = 274,
        Stat_Hide_in_Shadows_Modifier                                = 275,
        Stat_Detect_Illusion_Modifier                                = 276,
        Stat_Set_Traps_Modifier                                      = 277,
        Stat_To_Hit_Modifier                                         = 278,
        Button_Enable_Button                                         = 279,
        Spell_Effect_Wild_Magic                                      = 280,
        Stat_Wild_Magic                                              = 281,
        Script_Scripting_State_Modifier                              = 282,
        Use_EFF_File_Cursed                                          = 283,
        Stat_Melee_THAC0_Modifier                                    = 284,
        Stat_Melee_Weapon_Damage_Modifier                            = 285,
        Stat_Missile_Weapon_Damage_Modifier                          = 286,
        Graphics_Selection_Circle_Removal                            = 287,
        Stat_Fist_THAC0_Modifier                                     = 288,
        Stat_Fist_Damage_Modifier                                    = 289,
        Text_Change_Title                                            = 290,
        Graphics_Disable_Visual_Effect                               = 291,
        Protection_Backstab                                          = 292,
        Script_Enable_Offscreen_AI                                   = 293,
        Spell_Effect_Existance_Delay_Override                        = 294,
        Graphics_Disable_Permanent_Death                             = 295,
        Graphics_Protection_from_Specific_Animation                  = 296,
        Spell_Effect_Immunity_to_Turn_Undead                         = 297,
        Spell_Effect_Execute_Script_cut250a                          = 298,
        Spell_Effect_Chaos_Shield                                    = 299,
        Spell_Effect_NPCBump                                         = 300,
        Stat_Critical_Hit_Modifier                                   = 301,
        Item_Can_Use_Any_Item                                        = 302,
        Spell_Effect_Backstab_Every_Hit                              = 303,
        Mass_Raise_Dead                                              = 304,
        Stat_THAC0_Modifier_OffHand                                  = 305,
        Stat_THAC0_Modifier_OnHand                                   = 306,
        Ranger_Tracking_Ability                                      = 307,
        Protection_From_Tracking                                     = 308,
        Script_Modify_Local_Variable                                 = 309,
        Protection_from_Timestop                                     = 310,
        Spell_Random_Wish_Spell                                      = 311,
        Crash                                                        = 312,
        HighLevel_Ability_Denotation                                 = 313,
        Spell_Golem_Stoneskin                                        = 314,
        Graphics_Animation_Removal                                   = 315,
        Spell_Magical_Rest                                           = 316,
        State_Haste_2                                                = 317,
        Protection_from_Resource                                     = 318,
        Usability_Item_Usability                                     = 319,
        Change_Weather                                               = 320,
        Removal_Effects_specified_by_Resource                        = 321,
        Stat_Turn_Undead_Level                                       = 323,
        Protection_Immunity_to_Resource_and_Message                  = 324,
        Stat_Save_vs_all                                             = 325,
        Apply_Effects_List                                           = 326,
        Graphics_Icewind_Visual_Spell_Hit_plays_sound                = 327,
        State_Set_State                                              = 328,
        Spell_Effect_Slow_Poison                                     = 329,
        Text_Float_Text                                              = 330,
        Summon_Random_Monster_Summoning                              = 331,
        Stat_Specific_Damage_Modifier                                = 332,
        Spell_Effect_Static_Charge                                   = 333,
        Spell_Effect_Turn_Undead                                     = 334,
        Spell_Effect_Seven_Eyes                                      = 335,
        Graphics_Display_Eyes_Overlay                                = 336,
        Remove_Opcode                                                = 337,
        Disable_Rest                                                 = 338,
        Alter_Animation                                              = 339,
        Spell_Effect_Change_Backstab_Effect                          = 340,
        Spell_Effect_Change_Critical_Hit_Effect                      = 341,
        Animation_Override_Data                                      = 342,
        HP_Swap                                                      = 343,
        Enchantment_vs_creature_type                                 = 344,
        Enchantment_bonus                                            = 345,
        Save_vs_school_bonus                                         = 346,
        Stat_Ignore_Reputation_Breaking_Point                        = 360,
        Cast_spell_on_critical_miss                                  = 361,
        Critical_miss_bonus                                          = 362,
        Modal_state_check                                            = 363,
        Make_unselectable                                            = 365,
        Spell_Apply_Spell_On_Move                                    = 366,
        Minimum_base_stats                                           = 367,
    }
}
